### ISSUE TITLE
Default readMode: single possibly gives duplicate job

### ISSUE THREAD

**Issue by zllovesuki** [grantcarthew/node-rethinkdb-job-queue#43]
On my 3 nodes rDB setup, with 8 job subscribers, using your job queue produces duplicate job sometimes (eg .process() gets the same job twice). I think this is possibly due to the default readMode and therefore "not thread safe" or "race condition".

**Comment by grantcarthew** [comment]
You're right @zllovesuki. I'll fix it.

**Comment by grantcarthew** [comment]
Fixed in v2.1.0
[Change Log](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Change-Log)
[Documentation](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Options#queue-queryrunoptions-option)

Thanks for the feedback @zllovesuki

**Comment by zllovesuki** [comment]
Mmm, I'm still getting duplicate jobs. I'm not sure if this is caused by readMode.

**Comment by zllovesuki** [comment]
A little context, I was using Bull (redis backed) and rethinkdb-job-queue was used as a drop in replacement since my stack already has RethinkDB available.

**Comment by grantcarthew** [comment]
Oh, that's a shame @zllovesuki. The whole reason I make this queue was for your use case.

I placed the `readMode` opiton in the `query.run(conn[, options]) → promise` query calls. I didn't use the `db.table(name[, {readMode: 'single', identifierFormat: 'name'}]) → table` format.

From the RethinkDB documentation it should work the same.
Here: https://www.rethinkdb.com/api/javascript/run/
And here: https://www.rethinkdb.com/api/javascript/table/

I don't have a setup causing the issue right now. Can you do some more testing please?

**Comment by zllovesuki** [comment]
Sure thing, but I have to replicate the production environment first.

**Comment by grantcarthew** [comment]
Great. That would be a real help. If you can replicate the issue and try different approaches we should be able to track down a fix. I was and still am under the impression that the queries I have written in the module are atomic. With the change to `readMode: majority` as the default, the get queries should not return the same job on different processing nodes.

First thing I would try is putting the `readMode` into the `.table([options])` call in the `getNextJob()` function call.

In this file: https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-get-next-job.js

Take note of line 45 with the `.run(q.queryRunOptions)`. You could simply remove the `q.queryRunOptions` and leave that line as `.run()`, and move it to line 16. So changing line 16 from this `.table(q.name)` to `.table(q.name, q.queryRunOptions)`.

Note also that the `index.js` file points to the `dist` directory so either find the same lines in the transpiled code or, if running a modern Node.js version, change the `index.js` to point to `src/queue.js`.

Hope that makes sense.

**Comment by zllovesuki** [comment]
OK I backtracked the database and this is the object in which duplicate jobs occurred:

```
{
    "dateCreated": {
        "$reql_type$": "TIME",
        "epoch_time": 1484790189.586,
        "timezone": "+00:00"
    },
    "dateEnable": {
        "$reql_type$": "TIME",
        "epoch_time": 1484791089.627,
        "timezone": "+00:00"
    },
    "dateFinished": {
        "$reql_type$": "TIME",
        "epoch_time": 1484790192.705,
        "timezone": "+00:00"
    },
    "dateStarted": {
        "$reql_type$": "TIME",
        "epoch_time": 1484790189.627,
        "timezone": "+00:00"
    },
    "id": "025ced10-7d19-41d3-a7d4-390b37812dac",
    "log": [{
        "data": null,
        "date": {
            "$reql_type$": "TIME",
            "epoch_time": 1484790189.586,
            "timezone": "+00:00"
        },
        "message": "Job added to the queue",
        "processCount": 0,
        "queueId": "dermail-api-1:dermail:jobQueue:2515:50b01ffa-a6c3-4d07-ba6a-24a99ccdf08d",
        "retryCount": 0,
        "status": "waiting",
        "type": "information"
    }, {
        "date": {
            "$reql_type$": "TIME",
            "epoch_time": 1484790189.619,
            "timezone": "+00:00"
        },
        "message": "Job retrieved and active",
        "processCount": 0,
        "queueId": "dermail-api-2:dermail:jobQueue:17707:8d9a2b51-094f-4a5b-9a7c-82a15de03f14",
        "retryCount": 0,
        "status": "active",
        "type": "information"
    }, {
        "date": {
            "$reql_type$": "TIME",
            "epoch_time": 1484790189.627,
            "timezone": "+00:00"
        },
        "message": "Job retrieved and active",
        "processCount": 1,
        "queueId": "dermail-api-1:dermail:jobQueue:2515:7da3ba25-e00b-4c91-9bea-31e6ec60f07e",
        "retryCount": 0,
        "status": "active",
        "type": "information"
    }, {
        "data": {},
        "date": {
            "$reql_type$": "TIME",
            "epoch_time": 1484790192.408,
            "timezone": "+00:00"
        },
        "duration": 2789,
        "message": "completed",
        "processCount": 1,
        "queueId": "dermail-api-2:dermail:jobQueue:17707:8d9a2b51-094f-4a5b-9a7c-82a15de03f14",
        "retryCount": 0,
        "status": "completed",
        "type": "information"
    }, {
        "data": {},
        "date": {
            "$reql_type$": "TIME",
            "epoch_time": 1484790192.705,
            "timezone": "+00:00"
        },
        "duration": 3078,
        "message": "completed",
        "processCount": 2,
        "queueId": "dermail-api-1:dermail:jobQueue:2515:7da3ba25-e00b-4c91-9bea-31e6ec60f07e",
        "retryCount": 0,
        "status": "completed",
        "type": "information"
    }],
    "payload": [redacted],
    "priority": 40,
    "processCount": 2,
    "progress": 100,
    "queueId": "dermail-api-1:dermail:jobQueue:2515:7da3ba25-e00b-4c91-9bea-31e6ec60f07e",
    "repeat": false,
    "repeatDelay": 300000,
    "retryCount": 0,
    "retryDelay": 2000,
    "retryMax": 50,
    "status": "completed",
    "timeout": 900000,
    "type": "saveRX"
}
```

**Comment by zllovesuki** [comment]
I think you should have some sort of locks in place, "Job retrieved and active" was called in a very small time gap (race condition?)

**Comment by zllovesuki** [comment]
Possibly due to locking?

If I check for process punt before doing the actual job (job.processCount - job.retryCount > 1) then I can avoid the duplicate job.

**Comment by grantcarthew** [comment]
Hi @zllovesuki. Thanks for the logs. That helps a lot.

I see what you are suggesting with the process and retry count check, however this would be fixing the symptom not the cause. I was under the impression the get next RethinkDB query is atomic. The logs you have indicate this is not the case.

I will try to involve someone from the RethinkDB slack channel and see if we can get some input. I'm busy at the moment (8:32am here in Brisbane Australia). I'll try and get it done today.

Thanks for your help with this.

**Comment by grantcarthew** [comment]
Hey @zllovesuki. I think we have a solution. I have to try it and I haven't done that yet. Just letting you know.

The solution is to move the [filter condition in the get-next-job](https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-get-next-job.js#L19) query into the update method. Could even add a condition to ensure the job is not active within update. Here is an example from the RethinkDB docs:

```js
r.table("posts").get(1).update(function(post) {
    return r.branch(
        post("views").gt(100),
        {type: "hot"},
        {type: "normal"}
    )
}).run(conn, callback)
```

I'll work on it when I can and let you know once I have working code.

**Comment by grantcarthew** [comment]
@zllovesuki Done. Update to v2.1.1 and please test it out.

**Comment by zllovesuki** [comment]
@grantcarthew It does look like the new code is working (no more duplicate jobs). Thanks for the time and effort spent on this issue!

**Comment by grantcarthew** [comment]
Good to hear. Thanks also for your help in finding a solution.
